# Generated by Django 3.0.7 on 2020-07-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_book_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='note',
            field=models.TextField(null=True),
        ),
    ]
