# Generated by Django 3.0.7 on 2020-07-27 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_book_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='note',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='note',
            name='book',
        ),
        migrations.AddField(
            model_name='note',
            name='book',
            field=models.ManyToManyField(to='api.Book'),
        ),
    ]
