# Generated by Django 3.0.7 on 2020-07-28 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200727_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='page_number',
            field=models.IntegerField(null=True),
        ),
    ]
